openapi: 3.0.0
info:
  title: "LOG430"
  version: 0.1.9
# servers:
#   - url: http://api.example.com/v1
#   - url: http://staging-api.example.com
tags:
- name: IRouteCalculator
  description: Service that allow comparison of routes
- name: IService
  description: Basic endpoints that all micro services should implements
paths:
  /route/{origin}/{destination}:
    get:
      summary: Return the time between two points.
      description: Return the estimated route time between two points for a given provider.
      tags:
        - IRouteCalculator
      parameters:
        - in: path
          name: origin
          schema:
            type: string
          required: true
          description: "Coordinates of the origin point (Format : LAT,LONG)"
          example: 45.5944645,-73.4704491
        - in: path
          name: destination
          schema:
            type: string
          required: true
          description: "Coordinates of the destination point (Format : LAT,LONG)"
          example: 45.5944645,-73.4704491
      responses:
        '200':
          description: Information about the time required to drive from origin to destination
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/RouteCalulatorResponse'
    
  /api/kill:
    get:
      summary: Kill the service.
      description: This endpoint allow the ChaosMonkey to kill a given API.
      tags:
        - IRouteCalculator
      responses:
        '200':
          description: Information about the time required to drive from origin to destination
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/RouteCalulatorResponse'
    
components:
  schemas:
    RouteCalulatorResponse:
      type: object
      properties: 
        date: 
          type: string
          format: date-time
        origin:
          type: string
          format: lat,long
        destination:
          type: string
          format: lat,long
        duration:
          type: number
          description: Duration in minutes
        distance:
          type: number
          description: Distance in meters
        
            
